-- Generated by scripts/sync-feature-registry.ts — do not edit by hand.
-- Registry sync: manifests -> feature_flags, permissions, role_permissions.

create table if not exists public.feature_registry (
  key text primary key,
  name text not null,
  description text not null,
  icon text not null,
  nav_path text,
  nav_order int,
  nav_permission text,
  flag_key text not null,
  settings_path text,
  permissions jsonb not null default '[]'::jsonb,
  analytics jsonb not null default '{}'::jsonb,
  activity_actions text[] not null default '{}',
  usage_meters jsonb not null default '[]'::jsonb,
  data_tables text[] not null default '{}',
  synced_at timestamptz not null default now()
);
grant select on public.feature_registry to authenticated;
grant all on public.feature_registry to service_role;
alter table public.feature_registry enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='feature_registry' and policyname='feature_registry_select_all') then
    create policy "feature_registry_select_all" on public.feature_registry for select to authenticated using (true);
  end if;
end $$;

alter table public.permissions drop constraint if exists permissions_category_check;
alter table public.permissions add constraint permissions_category_check check (category in ('inbox', 'contacts', 'campaigns', 'templates', 'automations', 'analytics', 'compliance', 'settings', 'team', 'billing'));

-- Shared Inbox
insert into public.feature_flags (key, name, description, default_enabled)
values ('inbox', 'Shared Inbox', 'One shared place for the team to reply, assign and close conversations.', true)
on conflict (key) do update set name = excluded.name, description = excluded.description;
insert into public.permissions (key, name, description, category, min_role)
values ('inbox.view', 'View inbox', 'Open the shared inbox and read conversations.', 'inbox', 'agent')
on conflict (key) do update set name = excluded.name, description = excluded.description, category = excluded.category, min_role = excluded.min_role;
insert into public.permissions (key, name, description, category, min_role)
values ('inbox.reply', 'Reply in inbox', 'Send replies to customers from the shared inbox.', 'inbox', 'agent')
on conflict (key) do update set name = excluded.name, description = excluded.description, category = excluded.category, min_role = excluded.min_role;
insert into public.permissions (key, name, description, category, min_role)
values ('inbox.assign', 'Assign conversations', 'Assign a conversation to a teammate.', 'inbox', 'agent')
on conflict (key) do update set name = excluded.name, description = excluded.description, category = excluded.category, min_role = excluded.min_role;
insert into public.permissions (key, name, description, category, min_role)
values ('inbox.close', 'Close conversations', 'Mark conversations as closed.', 'inbox', 'admin')
on conflict (key) do update set name = excluded.name, description = excluded.description, category = excluded.category, min_role = excluded.min_role;
insert into public.feature_registry (
  key, name, description, icon, nav_path, nav_order, nav_permission, flag_key, settings_path,
  permissions, analytics, activity_actions, usage_meters, data_tables, synced_at
) values (
  'inbox', 'Shared Inbox', 'One shared place for the team to reply, assign and close conversations.', 'inbox', '/app/inbox', 10, 'inbox.view', 'inbox', null,
  '[{"key":"inbox.view","name":"View inbox","description":"Open the shared inbox and read conversations.","min_role":"agent"},{"key":"inbox.reply","name":"Reply in inbox","description":"Send replies to customers from the shared inbox.","min_role":"agent"},{"key":"inbox.assign","name":"Assign conversations","description":"Assign a conversation to a teammate.","min_role":"agent"},{"key":"inbox.close","name":"Close conversations","description":"Mark conversations as closed.","min_role":"admin"}]'::jsonb, '{"event_types":["message.inbound","message.outbound","conversation.closed"],"metrics":["first_response_median","first_response_p90","conversations_handled"],"dashboard_section":true,"section_id":"inbox","section_label":"Inbox & team","section_order":40}'::jsonb, array['conversation_assigned', 'conversation_closed']::text[], '[]'::jsonb, array['conversations', 'messages']::text[], now()
) on conflict (key) do update set
  name = excluded.name, description = excluded.description, icon = excluded.icon,
  nav_path = excluded.nav_path, nav_order = excluded.nav_order, nav_permission = excluded.nav_permission,
  flag_key = excluded.flag_key, settings_path = excluded.settings_path,
  permissions = excluded.permissions, analytics = excluded.analytics,
  activity_actions = excluded.activity_actions, usage_meters = excluded.usage_meters,
  data_tables = excluded.data_tables, synced_at = now();

-- Contacts
insert into public.feature_flags (key, name, description, default_enabled)
values ('contacts', 'Contacts', 'Your audience — contacts, tags, imports and saved segments.', true)
on conflict (key) do update set name = excluded.name, description = excluded.description;
insert into public.permissions (key, name, description, category, min_role)
values ('contacts.view', 'View contacts', 'Browse contacts and their details.', 'contacts', 'agent')
on conflict (key) do update set name = excluded.name, description = excluded.description, category = excluded.category, min_role = excluded.min_role;
insert into public.permissions (key, name, description, category, min_role)
values ('contacts.edit', 'Edit contacts', 'Create and edit contacts, tags and attributes.', 'contacts', 'marketer')
on conflict (key) do update set name = excluded.name, description = excluded.description, category = excluded.category, min_role = excluded.min_role;
insert into public.permissions (key, name, description, category, min_role)
values ('contacts.import', 'Import contacts', 'Bring contacts in from a CSV file.', 'contacts', 'marketer')
on conflict (key) do update set name = excluded.name, description = excluded.description, category = excluded.category, min_role = excluded.min_role;
insert into public.permissions (key, name, description, category, min_role)
values ('contacts.export', 'Export contacts', 'Download contact data.', 'contacts', 'admin')
on conflict (key) do update set name = excluded.name, description = excluded.description, category = excluded.category, min_role = excluded.min_role;
insert into public.permissions (key, name, description, category, min_role)
values ('contacts.delete', 'Delete contacts', 'Permanently remove contacts.', 'contacts', 'admin')
on conflict (key) do update set name = excluded.name, description = excluded.description, category = excluded.category, min_role = excluded.min_role;
insert into public.permissions (key, name, description, category, min_role)
values ('segments.manage', 'Manage segments', 'Create and edit saved audience segments.', 'contacts', 'marketer')
on conflict (key) do update set name = excluded.name, description = excluded.description, category = excluded.category, min_role = excluded.min_role;
insert into public.feature_registry (
  key, name, description, icon, nav_path, nav_order, nav_permission, flag_key, settings_path,
  permissions, analytics, activity_actions, usage_meters, data_tables, synced_at
) values (
  'contacts', 'Contacts', 'Your audience — contacts, tags, imports and saved segments.', 'contact', '/app/contacts', 20, 'contacts.view', 'contacts', '/app/settings',
  '[{"key":"contacts.view","name":"View contacts","description":"Browse contacts and their details.","min_role":"agent"},{"key":"contacts.edit","name":"Edit contacts","description":"Create and edit contacts, tags and attributes.","min_role":"marketer"},{"key":"contacts.import","name":"Import contacts","description":"Bring contacts in from a CSV file.","min_role":"marketer"},{"key":"contacts.export","name":"Export contacts","description":"Download contact data.","min_role":"admin"},{"key":"contacts.delete","name":"Delete contacts","description":"Permanently remove contacts.","min_role":"admin"},{"key":"segments.manage","name":"Manage segments","description":"Create and edit saved audience segments.","min_role":"marketer"}]'::jsonb, '{"event_types":["contact.created","contact.imported","contact.opt_changed"],"metrics":["new_contacts","contacts_by_source","opt_in_split","opt_outs_over_time"],"dashboard_section":true,"section_id":"contacts","section_label":"Contacts","section_order":30}'::jsonb, array['contact_created', 'contacts_imported', 'tag_created', 'optin_changed', 'segment_created', 'segment_deleted', 'lead_source_marker_created', 'lead_source_marker_deleted']::text[], '[{"key":"contacts_stored","name":"Contacts stored","unit":"contacts"}]'::jsonb, array['contacts', 'tags', 'contact_tags', 'contact_imports', 'segments', 'lead_source_markers']::text[], now()
) on conflict (key) do update set
  name = excluded.name, description = excluded.description, icon = excluded.icon,
  nav_path = excluded.nav_path, nav_order = excluded.nav_order, nav_permission = excluded.nav_permission,
  flag_key = excluded.flag_key, settings_path = excluded.settings_path,
  permissions = excluded.permissions, analytics = excluded.analytics,
  activity_actions = excluded.activity_actions, usage_meters = excluded.usage_meters,
  data_tables = excluded.data_tables, synced_at = now();

-- Campaigns
insert into public.feature_flags (key, name, description, default_enabled)
values ('campaigns', 'Campaigns', 'Broadcast an approved template to a segment of opted-in contacts.', true)
on conflict (key) do update set name = excluded.name, description = excluded.description;
insert into public.permissions (key, name, description, category, min_role)
values ('campaigns.view', 'View campaigns', 'See campaigns and their results.', 'campaigns', 'marketer')
on conflict (key) do update set name = excluded.name, description = excluded.description, category = excluded.category, min_role = excluded.min_role;
insert into public.permissions (key, name, description, category, min_role)
values ('campaigns.create', 'Create campaigns', 'Build and schedule a campaign.', 'campaigns', 'marketer')
on conflict (key) do update set name = excluded.name, description = excluded.description, category = excluded.category, min_role = excluded.min_role;
insert into public.permissions (key, name, description, category, min_role)
values ('campaigns.send', 'Send campaigns', 'Launch, pause and resume a campaign.', 'campaigns', 'marketer')
on conflict (key) do update set name = excluded.name, description = excluded.description, category = excluded.category, min_role = excluded.min_role;
insert into public.feature_registry (
  key, name, description, icon, nav_path, nav_order, nav_permission, flag_key, settings_path,
  permissions, analytics, activity_actions, usage_meters, data_tables, synced_at
) values (
  'campaigns', 'Campaigns', 'Broadcast an approved template to a segment of opted-in contacts.', 'megaphone', '/app/campaigns', 30, 'campaigns.view', 'campaigns', null,
  '[{"key":"campaigns.view","name":"View campaigns","description":"See campaigns and their results.","min_role":"marketer"},{"key":"campaigns.create","name":"Create campaigns","description":"Build and schedule a campaign.","min_role":"marketer"},{"key":"campaigns.send","name":"Send campaigns","description":"Launch, pause and resume a campaign.","min_role":"marketer"}]'::jsonb, '{"event_types":["campaign.launched","campaign.recipient_status"],"metrics":["recipients","delivered_rate","read_rate","replied_rate","failure_reasons"],"dashboard_section":true,"section_id":"campaigns","section_label":"Campaigns","section_order":20}'::jsonb, array['campaign_created', 'campaign_launched', 'campaign_controlled']::text[], '[{"key":"campaign_messages","name":"Campaign messages sent","unit":"messages"}]'::jsonb, array['campaigns', 'campaign_recipients']::text[], now()
) on conflict (key) do update set
  name = excluded.name, description = excluded.description, icon = excluded.icon,
  nav_path = excluded.nav_path, nav_order = excluded.nav_order, nav_permission = excluded.nav_permission,
  flag_key = excluded.flag_key, settings_path = excluded.settings_path,
  permissions = excluded.permissions, analytics = excluded.analytics,
  activity_actions = excluded.activity_actions, usage_meters = excluded.usage_meters,
  data_tables = excluded.data_tables, synced_at = now();

-- Message Templates
insert into public.feature_flags (key, name, description, default_enabled)
values ('templates', 'Message Templates', 'Pre-approved messages you can send at any time.', true)
on conflict (key) do update set name = excluded.name, description = excluded.description;
insert into public.permissions (key, name, description, category, min_role)
values ('templates.manage', 'Manage templates', 'Create, sync and submit message templates.', 'templates', 'marketer')
on conflict (key) do update set name = excluded.name, description = excluded.description, category = excluded.category, min_role = excluded.min_role;
insert into public.feature_registry (
  key, name, description, icon, nav_path, nav_order, nav_permission, flag_key, settings_path,
  permissions, analytics, activity_actions, usage_meters, data_tables, synced_at
) values (
  'templates', 'Message Templates', 'Pre-approved messages you can send at any time.', 'message-square-text', '/app/templates', 40, 'templates.manage', 'templates', null,
  '[{"key":"templates.manage","name":"Manage templates","description":"Create, sync and submit message templates.","min_role":"marketer"}]'::jsonb, '{"event_types":[],"metrics":[],"dashboard_section":false}'::jsonb, array['template_created', 'template_synced']::text[], '[]'::jsonb, array['message_templates']::text[], now()
) on conflict (key) do update set
  name = excluded.name, description = excluded.description, icon = excluded.icon,
  nav_path = excluded.nav_path, nav_order = excluded.nav_order, nav_permission = excluded.nav_permission,
  flag_key = excluded.flag_key, settings_path = excluded.settings_path,
  permissions = excluded.permissions, analytics = excluded.analytics,
  activity_actions = excluded.activity_actions, usage_meters = excluded.usage_meters,
  data_tables = excluded.data_tables, synced_at = now();

-- Automations
insert into public.feature_flags (key, name, description, default_enabled)
values ('automations', 'Automations', 'Welcome messages, keyword replies and off-hours cover.', true)
on conflict (key) do update set name = excluded.name, description = excluded.description;
insert into public.permissions (key, name, description, category, min_role)
values ('automations.manage', 'Manage automations', 'Create, edit and switch automations on or off.', 'automations', 'marketer')
on conflict (key) do update set name = excluded.name, description = excluded.description, category = excluded.category, min_role = excluded.min_role;
insert into public.feature_registry (
  key, name, description, icon, nav_path, nav_order, nav_permission, flag_key, settings_path,
  permissions, analytics, activity_actions, usage_meters, data_tables, synced_at
) values (
  'automations', 'Automations', 'Welcome messages, keyword replies and off-hours cover.', 'workflow', '/app/automations', 50, 'automations.manage', 'automations', null,
  '[{"key":"automations.manage","name":"Manage automations","description":"Create, edit and switch automations on or off.","min_role":"marketer"}]'::jsonb, '{"event_types":["automation.run","automation.skipped"],"metrics":["runs_sent","runs_skipped","skip_reasons"],"dashboard_section":true,"section_id":"automations","section_label":"Automations","section_order":50}'::jsonb, array['automation_created', 'automation_updated', 'automation_toggled', 'automation_deleted']::text[], '[]'::jsonb, array['automations', 'automation_runs']::text[], now()
) on conflict (key) do update set
  name = excluded.name, description = excluded.description, icon = excluded.icon,
  nav_path = excluded.nav_path, nav_order = excluded.nav_order, nav_permission = excluded.nav_permission,
  flag_key = excluded.flag_key, settings_path = excluded.settings_path,
  permissions = excluded.permissions, analytics = excluded.analytics,
  activity_actions = excluded.activity_actions, usage_meters = excluded.usage_meters,
  data_tables = excluded.data_tables, synced_at = now();

-- Analytics
insert into public.feature_flags (key, name, description, default_enabled)
values ('analytics', 'Analytics', 'Delivery, audience, response time and automation performance.', true)
on conflict (key) do update set name = excluded.name, description = excluded.description;
insert into public.permissions (key, name, description, category, min_role)
values ('analytics.view', 'View analytics', 'Open the analytics dashboard for this workspace.', 'analytics', 'marketer')
on conflict (key) do update set name = excluded.name, description = excluded.description, category = excluded.category, min_role = excluded.min_role;
insert into public.feature_registry (
  key, name, description, icon, nav_path, nav_order, nav_permission, flag_key, settings_path,
  permissions, analytics, activity_actions, usage_meters, data_tables, synced_at
) values (
  'analytics', 'Analytics', 'Delivery, audience, response time and automation performance.', 'bar-chart', '/app/analytics', 60, 'analytics.view', 'analytics', null,
  '[{"key":"analytics.view","name":"View analytics","description":"Open the analytics dashboard for this workspace.","min_role":"marketer"}]'::jsonb, '{"event_types":[],"metrics":["messages_sent","delivered","read","failed","replies"],"dashboard_section":true,"section_id":"overview","section_label":"Overview","section_order":10}'::jsonb, array[]::text[], '[]'::jsonb, array[]::text[], now()
) on conflict (key) do update set
  name = excluded.name, description = excluded.description, icon = excluded.icon,
  nav_path = excluded.nav_path, nav_order = excluded.nav_order, nav_permission = excluded.nav_permission,
  flag_key = excluded.flag_key, settings_path = excluded.settings_path,
  permissions = excluded.permissions, analytics = excluded.analytics,
  activity_actions = excluded.activity_actions, usage_meters = excluded.usage_meters,
  data_tables = excluded.data_tables, synced_at = now();

-- Opt-out & compliance
insert into public.feature_flags (key, name, description, default_enabled)
values ('compliance', 'Opt-out & compliance', 'Opt-out keywords, consent state and number quality monitoring.', true)
on conflict (key) do update set name = excluded.name, description = excluded.description;
insert into public.permissions (key, name, description, category, min_role)
values ('compliance.manage', 'Manage opt-out rules', 'Edit unsubscribe and resubscribe keywords for this workspace.', 'compliance', 'admin')
on conflict (key) do update set name = excluded.name, description = excluded.description, category = excluded.category, min_role = excluded.min_role;
insert into public.feature_registry (
  key, name, description, icon, nav_path, nav_order, nav_permission, flag_key, settings_path,
  permissions, analytics, activity_actions, usage_meters, data_tables, synced_at
) values (
  'compliance', 'Opt-out & compliance', 'Opt-out keywords, consent state and number quality monitoring.', 'shield-check', null, null, null, 'compliance', '/app/settings',
  '[{"key":"compliance.manage","name":"Manage opt-out rules","description":"Edit unsubscribe and resubscribe keywords for this workspace.","min_role":"admin"}]'::jsonb, '{"event_types":["quality.updated","contact.opted_out","contact.opted_in"],"metrics":["quality_history","opt_outs"],"dashboard_section":true,"section_id":"quality","section_label":"Number quality","section_order":60}'::jsonb, array['contact_opted_out', 'contact_opted_in', 'quality_changed', 'opt_out_keyword_created', 'opt_out_keyword_deleted']::text[], '[]'::jsonb, array['opt_out_keywords', 'whatsapp_quality_history']::text[], now()
) on conflict (key) do update set
  name = excluded.name, description = excluded.description, icon = excluded.icon,
  nav_path = excluded.nav_path, nav_order = excluded.nav_order, nav_permission = excluded.nav_permission,
  flag_key = excluded.flag_key, settings_path = excluded.settings_path,
  permissions = excluded.permissions, analytics = excluded.analytics,
  activity_actions = excluded.activity_actions, usage_meters = excluded.usage_meters,
  data_tables = excluded.data_tables, synced_at = now();

-- Settings
insert into public.feature_flags (key, name, description, default_enabled)
values ('settings', 'Settings', 'Workspace details and the connection that powers your messaging.', true)
on conflict (key) do update set name = excluded.name, description = excluded.description;
insert into public.permissions (key, name, description, category, min_role)
values ('settings.view', 'Open settings', 'See the workspace settings pages.', 'settings', 'agent')
on conflict (key) do update set name = excluded.name, description = excluded.description, category = excluded.category, min_role = excluded.min_role;
insert into public.permissions (key, name, description, category, min_role)
values ('settings.manage', 'Manage settings', 'Change workspace details and preferences.', 'settings', 'admin')
on conflict (key) do update set name = excluded.name, description = excluded.description, category = excluded.category, min_role = excluded.min_role;
insert into public.permissions (key, name, description, category, min_role)
values ('settings.whatsapp', 'Manage connection', 'Connect, disconnect or reconnect the business number.', 'settings', 'owner')
on conflict (key) do update set name = excluded.name, description = excluded.description, category = excluded.category, min_role = excluded.min_role;
insert into public.feature_registry (
  key, name, description, icon, nav_path, nav_order, nav_permission, flag_key, settings_path,
  permissions, analytics, activity_actions, usage_meters, data_tables, synced_at
) values (
  'settings', 'Settings', 'Workspace details and the connection that powers your messaging.', 'settings', '/app/settings', 70, 'settings.view', 'settings', '/app/settings',
  '[{"key":"settings.view","name":"Open settings","description":"See the workspace settings pages.","min_role":"agent"},{"key":"settings.manage","name":"Manage settings","description":"Change workspace details and preferences.","min_role":"admin"},{"key":"settings.whatsapp","name":"Manage connection","description":"Connect, disconnect or reconnect the business number.","min_role":"owner"}]'::jsonb, '{"event_types":[],"metrics":[],"dashboard_section":false}'::jsonb, array['organization.created', 'organization.updated', 'user.logged_in']::text[], '[]'::jsonb, array['organizations', 'whatsapp_accounts']::text[], now()
) on conflict (key) do update set
  name = excluded.name, description = excluded.description, icon = excluded.icon,
  nav_path = excluded.nav_path, nav_order = excluded.nav_order, nav_permission = excluded.nav_permission,
  flag_key = excluded.flag_key, settings_path = excluded.settings_path,
  permissions = excluded.permissions, analytics = excluded.analytics,
  activity_actions = excluded.activity_actions, usage_meters = excluded.usage_meters,
  data_tables = excluded.data_tables, synced_at = now();

-- Team
insert into public.feature_flags (key, name, description, default_enabled)
values ('team', 'Team', 'Teammates, roles, invitations and permission overrides.', true)
on conflict (key) do update set name = excluded.name, description = excluded.description;
insert into public.permissions (key, name, description, category, min_role)
values ('team.manage', 'Manage team', 'Invite teammates, change roles and adjust permissions.', 'team', 'admin')
on conflict (key) do update set name = excluded.name, description = excluded.description, category = excluded.category, min_role = excluded.min_role;
insert into public.feature_registry (
  key, name, description, icon, nav_path, nav_order, nav_permission, flag_key, settings_path,
  permissions, analytics, activity_actions, usage_meters, data_tables, synced_at
) values (
  'team', 'Team', 'Teammates, roles, invitations and permission overrides.', 'users', null, null, null, 'team', '/app/settings',
  '[{"key":"team.manage","name":"Manage team","description":"Invite teammates, change roles and adjust permissions.","min_role":"admin"}]'::jsonb, '{"event_types":[],"metrics":[],"dashboard_section":false}'::jsonb, array['member.invited', 'invitation.accepted', 'member.role_changed', 'member.removed', 'member.permission_overridden', 'member.permission_reset']::text[], '[{"key":"seats","name":"Team seats","unit":"seats"}]'::jsonb, array['organization_members', 'invitations', 'member_permissions']::text[], now()
) on conflict (key) do update set
  name = excluded.name, description = excluded.description, icon = excluded.icon,
  nav_path = excluded.nav_path, nav_order = excluded.nav_order, nav_permission = excluded.nav_permission,
  flag_key = excluded.flag_key, settings_path = excluded.settings_path,
  permissions = excluded.permissions, analytics = excluded.analytics,
  activity_actions = excluded.activity_actions, usage_meters = excluded.usage_meters,
  data_tables = excluded.data_tables, synced_at = now();

-- Billing
insert into public.feature_flags (key, name, description, default_enabled)
values ('billing', 'Billing', 'Plan, usage and invoices for this workspace.', false)
on conflict (key) do update set name = excluded.name, description = excluded.description;
insert into public.permissions (key, name, description, category, min_role)
values ('billing.manage', 'Manage billing', 'See and change the plan and payment details.', 'billing', 'owner')
on conflict (key) do update set name = excluded.name, description = excluded.description, category = excluded.category, min_role = excluded.min_role;
insert into public.feature_registry (
  key, name, description, icon, nav_path, nav_order, nav_permission, flag_key, settings_path,
  permissions, analytics, activity_actions, usage_meters, data_tables, synced_at
) values (
  'billing', 'Billing', 'Plan, usage and invoices for this workspace.', 'credit-card', null, null, null, 'billing', '/app/settings',
  '[{"key":"billing.manage","name":"Manage billing","description":"See and change the plan and payment details.","min_role":"owner"}]'::jsonb, '{"event_types":[],"metrics":[],"dashboard_section":false}'::jsonb, array[]::text[], '[]'::jsonb, array[]::text[], now()
) on conflict (key) do update set
  name = excluded.name, description = excluded.description, icon = excluded.icon,
  nav_path = excluded.nav_path, nav_order = excluded.nav_order, nav_permission = excluded.nav_permission,
  flag_key = excluded.flag_key, settings_path = excluded.settings_path,
  permissions = excluded.permissions, analytics = excluded.analytics,
  activity_actions = excluded.activity_actions, usage_meters = excluded.usage_meters,
  data_tables = excluded.data_tables, synced_at = now();

-- Role defaults derived from each permission's min_role.
insert into public.role_permissions (role, permission_key)
select 'owner', k from unnest(array['inbox.view', 'inbox.reply', 'inbox.assign', 'inbox.close', 'contacts.view', 'contacts.edit', 'contacts.import', 'contacts.export', 'contacts.delete', 'segments.manage', 'campaigns.view', 'campaigns.create', 'campaigns.send', 'templates.manage', 'automations.manage', 'analytics.view', 'compliance.manage', 'settings.view', 'settings.manage', 'settings.whatsapp', 'team.manage', 'billing.manage']::text[]) as k
on conflict do nothing;
insert into public.role_permissions (role, permission_key)
select 'admin', k from unnest(array['inbox.view', 'inbox.reply', 'inbox.assign', 'inbox.close', 'contacts.view', 'contacts.edit', 'contacts.import', 'contacts.export', 'contacts.delete', 'segments.manage', 'campaigns.view', 'campaigns.create', 'campaigns.send', 'templates.manage', 'automations.manage', 'analytics.view', 'compliance.manage', 'settings.view', 'settings.manage', 'team.manage']::text[]) as k
on conflict do nothing;
insert into public.role_permissions (role, permission_key)
select 'marketer', k from unnest(array['inbox.view', 'inbox.reply', 'inbox.assign', 'contacts.view', 'contacts.edit', 'contacts.import', 'segments.manage', 'campaigns.view', 'campaigns.create', 'campaigns.send', 'templates.manage', 'automations.manage', 'analytics.view', 'settings.view']::text[]) as k
on conflict do nothing;
insert into public.role_permissions (role, permission_key)
select 'agent', k from unnest(array['inbox.view', 'inbox.reply', 'inbox.assign', 'contacts.view', 'settings.view']::text[]) as k
on conflict do nothing;

-- Drift: rows the database still holds that no manifest declares.
create or replace view public.feature_registry_drift as
  select 'feature_flag'::text as kind, ff.key as identifier, null::text as detail
  from public.feature_flags ff
  where not exists (select 1 from public.feature_registry r where r.flag_key = ff.key)
  union all
  select 'permission', p.key, p.category
  from public.permissions p
  where not exists (
    select 1 from public.feature_registry r
    where r.permissions @> jsonb_build_array(jsonb_build_object('key', p.key))
  )
  union all
  select 'role_permission', rp.permission_key, rp.role
  from public.role_permissions rp
  where not exists (
    select 1 from public.feature_registry r
    where r.permissions @> jsonb_build_array(jsonb_build_object('key', rp.permission_key))
  );
grant select on public.feature_registry_drift to authenticated;
grant select on public.feature_registry_drift to service_role;
