-- Batch 10B (3): Supabase security advisor items.
-- Idempotent. Apply by hand to the Mumbai project (hcsacmqzspnfqoftoifu); do not auto-apply.
-- Nothing here changes data, and nothing the app calls today loses access.
--
-- Advisor findings this file closes (live advisor, 5 Oct 2026):
--   ERROR  security_definer_view                      public.feature_registry_drift
--   WARN   anon/authenticated_security_definer_function_executable
--            public.trg_ai_agent_mode_guard()
--            public.trg_ai_runs_welcome_credits()
--            public.trg_org_defaults_on_insert()
--            public.trg_org_plan_assigned_before()
-- Also hardened the same way (trigger-only, SECURITY INVOKER, but still
-- executable by anon/authenticated through PUBLIC):
--            public.ai_skills_guard(), public.ai_task_models_validate(),
--            public.freeze_contact_source(), public.guard_org_markup(),
--            public.trg_guard_campaign_privileged_columns(),
--            public.trg_guard_conversation_privileged_columns(),
--            public.trg_guard_org_privileged_columns()
--
-- NOT code (dashboard setting): leaked-password protection. Supabase dashboard
-- → Authentication → Sign In / Providers → Email → turn on "Prevent use of
-- leaked passwords" (checks new passwords against HaveIBeenPwned). Existing
-- passwords keep working; only new/changed passwords are checked.

-- ---------------------------------------------------------------------------
-- 1. feature_registry_drift
-- What it is: a review aid listing feature flags / permissions that no
-- feature manifest declares (generated by scripts/sync-feature-registry.ts).
-- Who reads it today: no application code (nothing under src/ queries it);
-- the platform team reads it from the SQL editor (postgres). It was created
-- without security_invoker, so it ran with its owner's rights and was granted
-- to anon + authenticated: any visitor could list internal flag/permission
-- keys through /rest/v1/feature_registry_drift.
-- After: it runs with the caller's rights and only service_role (and the
-- owner, postgres) can read it. The SQL editor is unaffected.
DO $$
BEGIN
  IF to_regclass('public.feature_registry_drift') IS NOT NULL THEN
    EXECUTE 'ALTER VIEW public.feature_registry_drift SET (security_invoker = true)';
    EXECUTE 'REVOKE ALL ON public.feature_registry_drift FROM PUBLIC, anon, authenticated';
    EXECUTE 'GRANT SELECT ON public.feature_registry_drift TO service_role';
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 2. Trigger-only functions callable by anon/authenticated
-- Each function below RETURNS trigger and is used only by the trigger named
-- next to it. Postgres refuses to call a trigger function directly ("trigger
-- functions can only be called as triggers"), so no RPC, server route or
-- client calls any of them today — the grant only made them show up in the
-- exposed API. EXECUTE on a trigger function is checked when the trigger is
-- created, never when it fires: the triggers keep firing for every role,
-- exactly as the 20 trigger functions already restricted to postgres +
-- service_role do today (guard_last_owner, trg_ai_runs_billing,
-- trg_messages_billing, log_super_admin_write, …).
--
--   function                                   trigger (table)
--   trg_ai_agent_mode_guard (DEFINER)          ai_agent_mode_guard (ai_agents)
--   trg_ai_runs_welcome_credits (DEFINER)      ai_runs_welcome_credits (ai_runs)
--   trg_org_defaults_on_insert (DEFINER)       org_defaults_on_insert (organizations)
--   trg_org_plan_assigned_before (DEFINER)     org_plan_assigned_before (organizations)
--   ai_skills_guard                            ai_skills_guard_trg (ai_skills)
--   ai_task_models_validate                    ai_task_models_validate_trg (ai_task_models)
--   freeze_contact_source                      freeze_contact_source (contacts)
--   guard_org_markup                           organization_ai_settings_markup_guard (organization_ai_settings)
--   trg_guard_campaign_privileged_columns      aaa_guard_campaign_privileged_columns (campaigns)
--   trg_guard_conversation_privileged_columns  aaa_guard_conversation_privileged_columns (conversations)
--   trg_guard_org_privileged_columns           aaa_guard_org_privileged_columns (organizations)
DO $$
DECLARE
  fn text;
BEGIN
  FOREACH fn IN ARRAY ARRAY[
    'trg_ai_agent_mode_guard',
    'trg_ai_runs_welcome_credits',
    'trg_org_defaults_on_insert',
    'trg_org_plan_assigned_before',
    'ai_skills_guard',
    'ai_task_models_validate',
    'freeze_contact_source',
    'guard_org_markup',
    'trg_guard_campaign_privileged_columns',
    'trg_guard_conversation_privileged_columns',
    'trg_guard_org_privileged_columns'
  ] LOOP
    -- Only the zero-argument trigger function of that name; skipped if absent
    -- or (defensively) if it isn't a trigger function.
    IF EXISTS (
      SELECT 1
      FROM pg_proc p
      JOIN pg_namespace n ON n.oid = p.pronamespace
      WHERE n.nspname = 'public'
        AND p.proname = fn
        AND p.pronargs = 0
        AND p.prorettype = 'trigger'::regtype
    ) THEN
      EXECUTE format('REVOKE EXECUTE ON FUNCTION public.%I() FROM PUBLIC, anon, authenticated', fn);
      EXECUTE format('GRANT EXECUTE ON FUNCTION public.%I() TO service_role', fn);
    END IF;
  END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- Verify after applying (expect: no rows; and the view shows security_invoker):
--   SELECT p.proname FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
--   WHERE n.nspname = 'public' AND p.prorettype = 'trigger'::regtype
--     AND (has_function_privilege('anon', p.oid, 'EXECUTE')
--       OR has_function_privilege('authenticated', p.oid, 'EXECUTE'));
--   SELECT reloptions FROM pg_class WHERE oid = 'public.feature_registry_drift'::regclass;
--
-- Left as they are, on purpose (still listed by the advisor):
--   invitation_preview(text) for anon — the /join/$token page shows the invite
--     before sign-in. Other authenticated SECURITY DEFINER RPCs (has_org_role,
--     is_super_admin, analytics_*, match_knowledge_chunks, …) are called by
--     the app and by RLS policies and check membership themselves.
--   billing_fy / ist_month search_path, pg_net / vector in public, and the
--     service-role-only tables with RLS and no policies — separate changes.
