import { getServiceClient } from "@/lib/whatsapp-webhook.server";
import { ensureInvoicePdf, deliverInvoice } from "@/lib/invoices.server";
const s = getServiceClient();
const { data: inv } = await s.from("invoices").select("id, invoice_number, pdf_path, pdf_error, sent").eq("invoice_number", "AD/2026-27/00010").maybeSingle();
console.log("before", inv);
const path = await ensureInvoicePdf(s, String(inv!["id"]), { force: true });
console.log("pdf_path", path);
const del = await deliverInvoice(s, String(inv!["id"]), { fallbackToQueue: true });
console.log("deliver", del);
const { data: after } = await s.from("invoices").select("invoice_number, pdf_path, pdf_error, sent").eq("id", inv!["id"]).maybeSingle();
console.log("after", after);
