/**
 * Generates the registry sync migration from the feature manifests.
 *
 * Run:  bun run scripts/sync-feature-registry.ts > supabase/aidwar-migrations/<date>_feature_registry.sql
 *
 * The generated SQL only ever upserts. Rows in the database that no manifest
 * declares are never deleted — they surface in public.feature_registry_drift
 * so removing a feature stays a deliberate decision.
 */
import { FEATURES, roleDefaults, type OrgRole } from "../src/lib/feature-registry";

const q = (v: string | null | undefined) => (v == null ? "null" : `'${v.replace(/'/g, "''")}'`);
const arr = (v: string[]) => `array[${v.map((x) => q(x)).join(", ")}]::text[]`;
const json = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;
const ROLES: OrgRole[] = ["owner", "admin", "marketer", "agent"];

const lines: string[] = [];
lines.push("-- Generated by scripts/sync-feature-registry.ts — do not edit by hand.");
lines.push("-- Registry sync: manifests -> feature_flags, permissions, role_permissions.");
lines.push("");
lines.push(`create table if not exists public.feature_registry (
  key text primary key,
  name text not null,
  description text not null,
  icon text not null,
  nav_path text,
  nav_order int,
  nav_permission text,
  flag_key text not null,
  settings_path text,
  permissions jsonb not null default '[]'::jsonb,
  analytics jsonb not null default '{}'::jsonb,
  activity_actions text[] not null default '{}',
  usage_meters jsonb not null default '[]'::jsonb,
  data_tables text[] not null default '{}',
  synced_at timestamptz not null default now()
);`);
lines.push("grant select on public.feature_registry to authenticated;");
lines.push("grant all on public.feature_registry to service_role;");
lines.push("alter table public.feature_registry enable row level security;");
lines.push(`do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='feature_registry' and policyname='feature_registry_select_all') then
    create policy "feature_registry_select_all" on public.feature_registry for select to authenticated using (true);
  end if;
end $$;`);
lines.push("");

// Permission categories are now feature keys, so each feature gets its own
// section in the permission editor.
lines.push("alter table public.permissions drop constraint if exists permissions_category_check;");
lines.push("");

for (const f of FEATURES) {
  lines.push(`-- ${f.name}`);
  lines.push(`insert into public.feature_flags (key, name, description, default_enabled)
values (${q(f.flag_key)}, ${q(f.name)}, ${q(f.description)}, ${f.flag_default_enabled})
on conflict (key) do update set name = excluded.name, description = excluded.description;`);

  for (const p of f.permissions) {
    lines.push(`insert into public.permissions (key, name, description, category, min_role)
values (${q(p.key)}, ${q(p.name)}, ${q(p.description)}, ${q(f.key)}, ${q(p.min_role)})
on conflict (key) do update set name = excluded.name, description = excluded.description, category = excluded.category, min_role = excluded.min_role;`);
  }

  lines.push(`insert into public.feature_registry (
  key, name, description, icon, nav_path, nav_order, nav_permission, flag_key, settings_path,
  permissions, analytics, activity_actions, usage_meters, data_tables, synced_at
) values (
  ${q(f.key)}, ${q(f.name)}, ${q(f.description)}, ${q(f.icon)}, ${q(f.nav_path)}, ${f.nav_order ?? "null"}, ${q(f.nav_permission)}, ${q(f.flag_key)}, ${q(f.settings_path)},
  ${json(f.permissions)}, ${json(f.analytics)}, ${arr(f.activity_actions)}, ${json(f.usage_meters ?? [])}, ${arr(f.data_tables)}, now()
) on conflict (key) do update set
  name = excluded.name, description = excluded.description, icon = excluded.icon,
  nav_path = excluded.nav_path, nav_order = excluded.nav_order, nav_permission = excluded.nav_permission,
  flag_key = excluded.flag_key, settings_path = excluded.settings_path,
  permissions = excluded.permissions, analytics = excluded.analytics,
  activity_actions = excluded.activity_actions, usage_meters = excluded.usage_meters,
  data_tables = excluded.data_tables, synced_at = now();`);
  lines.push("");
}

lines.push("-- Role defaults derived from each permission's min_role.");
for (const role of ROLES) {
  const keys = roleDefaults(role);
  lines.push(`insert into public.role_permissions (role, permission_key)
select ${q(role)}, k from unnest(${arr(keys)}) as k
on conflict do nothing;`);
}
lines.push("");

lines.push(`-- Drift: rows the database still holds that no manifest declares.
create or replace view public.feature_registry_drift as
  select 'feature_flag'::text as kind, ff.key as identifier, null::text as detail
  from public.feature_flags ff
  where not exists (select 1 from public.feature_registry r where r.flag_key = ff.key)
  union all
  select 'permission', p.key, p.category
  from public.permissions p
  where not exists (
    select 1 from public.feature_registry r
    where r.permissions @> jsonb_build_array(jsonb_build_object('key', p.key))
  )
  union all
  select 'role_permission', rp.permission_key, rp.role
  from public.role_permissions rp
  where not exists (
    select 1 from public.feature_registry r
    where r.permissions @> jsonb_build_array(jsonb_build_object('key', rp.permission_key))
  );`);
// Re-added only after every permission row carries a feature key as category.
lines.push(
  `alter table public.permissions add constraint permissions_category_check check (category in (${FEATURES.map(
    (f) => q(f.key),
  ).join(", ")}));`,
);
lines.push("");
lines.push("grant select on public.feature_registry_drift to authenticated;");
lines.push("grant select on public.feature_registry_drift to service_role;");

process.stdout.write(lines.join("\n") + "\n");
