/**
 * Generates the registry sync migration from the feature manifests.
 *
 * Run:  bun run scripts/sync-feature-registry.ts > supabase/aidwar-migrations/<date>_feature_registry.sql
 *
 * The generated SQL only ever upserts. Rows in the database that no manifest
 * declares are never deleted — they surface in public.feature_registry_drift
 * so removing a feature stays a deliberate decision.
 */
import { spawnSync } from "node:child_process";
import { FEATURES, roleDefaults, type OrgRole } from "../src/lib/feature-registry";

const q = (v: string | null | undefined) => (v == null ? "null" : `'${v.replace(/'/g, "''")}'`);
const arr = (v: string[]) => `array[${v.map((x) => q(x)).join(", ")}]::text[]`;
const json = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;
const ROLES: OrgRole[] = ["owner", "admin", "marketer", "agent"];

/**
 * The database row is the source of truth for depends_on, permissions and
 * data_tables. If a manifest would blank or change one of those, stop and
 * print the difference instead of generating SQL that overwrites it.
 */
function guardAgainstDrift() {
  const url = process.env["AIDWAR_MUMBAI_DB_URL"];
  if (!url) {
    process.stderr.write("! AIDWAR_MUMBAI_DB_URL not set — skipping the database drift check.\n");
    return;
  }
  const res = spawnSync(
    "psql",
    [url, "-At", "-c", "select key, coalesce(depends_on,'{}'), coalesce(permissions,'[]'::jsonb), coalesce(data_tables,'{}') from public.feature_registry"],
    { encoding: "utf8" },
  );
  if (res.status !== 0) {
    process.stderr.write(`! could not read feature_registry: ${res.stderr}\n`);
    process.exit(1);
  }
  const arrOf = (v: string) => (v === "{}" ? [] : v.slice(1, -1).split(",").map((x) => x.replace(/^"|"$/g, "")));
  const problems: string[] = [];
  for (const line of res.stdout.trim().split("\n").filter(Boolean)) {
    const [key = "", dependsRaw = "{}", permsRaw = "[]", tablesRaw = "{}"] = line.split("|");
    const f = FEATURES.find((x) => x.key === key);
    if (!f) continue; // drift view already surfaces rows no manifest declares
    const dbDepends = arrOf(dependsRaw).sort();
    const dbTables = arrOf(tablesRaw).sort();
    const dbPerms = (JSON.parse(permsRaw) as { key: string }[]).map((p) => p.key).sort();
    const cmp = (label: string, db: string[], manifest: string[]) => {
      const a = [...db].sort().join(", ");
      const b = [...manifest].sort().join(", ");
      if (a !== b) problems.push(`  ${key}.${label}\n    database: [${a}]\n    manifest: [${b}]`);
    };
    cmp("depends_on", dbDepends, f.depends_on);
    cmp("data_tables", dbTables, f.data_tables);
    cmp("permissions", dbPerms, f.permissions.map((p) => p.key));
  }
  if (problems.length > 0) {
    process.stderr.write(
      "Registry sync stopped — the manifest disagrees with the database.\n" +
        "The database row is the source of truth; update the manifest to match.\n\n" +
        problems.join("\n") + "\n",
    );
    process.exit(1);
  }
}

guardAgainstDrift();

const lines: string[] = [];
lines.push("-- Generated by scripts/sync-feature-registry.ts — do not edit by hand.");
lines.push("-- Registry sync: manifests -> feature_flags, permissions, role_permissions.");
lines.push("");
lines.push(`create table if not exists public.feature_registry (
  key text primary key,
  name text not null,
  description text not null,
  icon text not null,
  nav_path text,
  nav_order int,
  nav_permission text,
  flag_key text not null,
  settings_path text,
  permissions jsonb not null default '[]'::jsonb,
  analytics jsonb not null default '{}'::jsonb,
  activity_actions text[] not null default '{}',
  usage_meters jsonb not null default '[]'::jsonb,
  ai_tools jsonb not null default '[]'::jsonb,
  data_tables text[] not null default '{}',
  depends_on text[] not null default '{}',
  synced_at timestamptz not null default now()
);`);
lines.push("alter table public.feature_registry add column if not exists ai_tools jsonb not null default '[]'::jsonb;");
lines.push("alter table public.feature_registry add column if not exists depends_on text[] not null default '{}';");
lines.push("grant select on public.feature_registry to authenticated;");
lines.push("grant all on public.feature_registry to service_role;");
lines.push("alter table public.feature_registry enable row level security;");
lines.push(`do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='feature_registry' and policyname='feature_registry_select_all') then
    create policy "feature_registry_select_all" on public.feature_registry for select to authenticated using (true);
  end if;
end $$;`);
lines.push("");

// Permission categories are now feature keys, so each feature gets its own
// section in the permission editor.
lines.push("alter table public.permissions drop constraint if exists permissions_category_check;");
lines.push("");

for (const f of FEATURES) {
  lines.push(`-- ${f.name}`);
  lines.push(`insert into public.feature_flags (key, name, description, default_enabled)
values (${q(f.flag_key)}, ${q(f.name)}, ${q(f.description)}, ${f.flag_default_enabled})
on conflict (key) do update set name = excluded.name, description = excluded.description;`);

  for (const p of f.permissions) {
    lines.push(`insert into public.permissions (key, name, description, category, min_role)
values (${q(p.key)}, ${q(p.name)}, ${q(p.description)}, ${q(f.key)}, ${q(p.min_role)})
on conflict (key) do update set name = excluded.name, description = excluded.description, category = excluded.category, min_role = excluded.min_role;`);
  }

  lines.push(`insert into public.feature_registry (
  key, name, description, icon, nav_path, nav_order, nav_permission, flag_key, settings_path,
  permissions, analytics, activity_actions, usage_meters, ai_tools, data_tables, depends_on, synced_at
) values (
  ${q(f.key)}, ${q(f.name)}, ${q(f.description)}, ${q(f.icon)}, ${q(f.nav_path)}, ${f.nav_order ?? "null"}, ${q(f.nav_permission)}, ${q(f.flag_key)}, ${q(f.settings_path)},
  ${json(f.permissions)}, ${json(f.analytics)}, ${arr(f.activity_actions)}, ${json(f.usage_meters ?? [])}, ${json(f.ai_tools ?? [])}, ${arr(f.data_tables)}, ${arr(f.depends_on)}, now()
) on conflict (key) do update set
  name = excluded.name, description = excluded.description, icon = excluded.icon,
  nav_path = excluded.nav_path, nav_order = excluded.nav_order, nav_permission = excluded.nav_permission,
  flag_key = excluded.flag_key, settings_path = excluded.settings_path,
  permissions = case when jsonb_array_length(excluded.permissions) = 0 then feature_registry.permissions else excluded.permissions end,
  analytics = excluded.analytics,
  activity_actions = excluded.activity_actions, usage_meters = excluded.usage_meters,
  ai_tools = excluded.ai_tools,
  data_tables = case when cardinality(excluded.data_tables) = 0 then feature_registry.data_tables else excluded.data_tables end,
  depends_on = case when cardinality(excluded.depends_on) = 0 then feature_registry.depends_on else excluded.depends_on end,
  synced_at = now();`);
  lines.push("");
}

lines.push("-- Role defaults derived from each permission's min_role.");
for (const role of ROLES) {
  const keys = roleDefaults(role);
  lines.push(`insert into public.role_permissions (role, permission_key)
select ${q(role)}, k from unnest(${arr(keys)}) as k
on conflict do nothing;`);
}
lines.push("");

lines.push(`-- Drift: rows the database still holds that no manifest declares.
create or replace view public.feature_registry_drift as
  select 'feature_flag'::text as kind, ff.key as identifier, null::text as detail
  from public.feature_flags ff
  where not exists (select 1 from public.feature_registry r where r.flag_key = ff.key)
  union all
  select 'permission', p.key, p.category
  from public.permissions p
  where not exists (
    select 1 from public.feature_registry r
    where r.permissions @> jsonb_build_array(jsonb_build_object('key', p.key))
  )
  union all
  select 'role_permission', rp.permission_key, rp.role
  from public.role_permissions rp
  where not exists (
    select 1 from public.feature_registry r
    where r.permissions @> jsonb_build_array(jsonb_build_object('key', rp.permission_key))
  );`);
// Re-added only after every permission row carries a feature key as category.
lines.push(
  `alter table public.permissions add constraint permissions_category_check check (category in (${FEATURES.map(
    (f) => q(f.key),
  ).join(", ")}));`,
);
lines.push("");
lines.push("grant select on public.feature_registry_drift to authenticated;");
lines.push("grant select on public.feature_registry_drift to service_role;");

process.stdout.write(lines.join("\n") + "\n");
