/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as AdminFlagsRouteImport } from './routes/admin/flags'
import { Route as AdminOrganizationsRouteImport } from './routes/admin/organizations'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiPermissionsRouteImport } from './routes/api/permissions'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as AppAutomationsRouteImport } from './routes/app/automations'
import { Route as AppContactsRouteImport } from './routes/app/contacts'
import { Route as AppInboxRouteImport } from './routes/app/inbox'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppTemplatesRouteImport } from './routes/app/templates'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as ApiAiToolsRouteImport } from './routes/api/ai/tools'
import { Route as ApiCampaignsAudienceRouteImport } from './routes/api/campaigns/audience'
import { Route as ApiCampaignsControlRouteImport } from './routes/api/campaigns/control'
import { Route as ApiCampaignsLaunchRouteImport } from './routes/api/campaigns/launch'
import { Route as ApiContactsEvaluateSegmentRouteImport } from './routes/api/contacts/evaluate-segment'
import { Route as ApiContactsImportRouteImport } from './routes/api/contacts/import'
import { Route as ApiIntegrationsShopifyRouteImport } from './routes/api/integrations/shopify'
import { Route as ApiInternalCampaignWorkerRouteImport } from './routes/api/internal/campaign-worker'
import { Route as ApiInternalFlowWorkerRouteImport } from './routes/api/internal/flow-worker'
import { Route as ApiInternalReprocessEventsRouteImport } from './routes/api/internal/reprocess-events'
import { Route as ApiInternalShopifySyncWorkerRouteImport } from './routes/api/internal/shopify-sync-worker'
import { Route as ApiInternalVersionRouteImport } from './routes/api/internal/version'
import { Route as ApiPublicShopifyCallbackRouteImport } from './routes/api/public/shopify-callback'
import { Route as ApiPublicShopifyWebhookRouteImport } from './routes/api/public/shopify-webhook'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp-webhook'
import { Route as ApiWhatsappConnectRouteImport } from './routes/api/whatsapp/connect'
import { Route as ApiWhatsappEsConfigRouteImport } from './routes/api/whatsapp/es-config'
import { Route as ApiWhatsappEsExchangeRouteImport } from './routes/api/whatsapp/es-exchange'
import { Route as ApiWhatsappRefreshQualityRouteImport } from './routes/api/whatsapp/refresh-quality'
import { Route as ApiWhatsappSendMessageRouteImport } from './routes/api/whatsapp/send-message'
import { Route as ApiWhatsappTemplatesRouteImport } from './routes/api/whatsapp/templates'
import { Route as ApiWhatsappTokenStatusRouteImport } from './routes/api/whatsapp/token-status'
import { Route as AppCampaignsIndexRouteImport } from './routes/app/campaigns.index'
import { Route as AppCampaignsIdRouteImport } from './routes/app/campaigns.$id'
import { Route as AppFlowsIndexRouteImport } from './routes/app/flows.index'
import { Route as ApiShopifyWebhooksCustomersDataRequestRouteImport } from './routes/api/shopify/webhooks/customers-data-request'
import { Route as ApiShopifyWebhooksCustomersRedactRouteImport } from './routes/api/shopify/webhooks/customers-redact'
import { Route as ApiShopifyWebhooksShopRedactRouteImport } from './routes/api/shopify/webhooks/shop-redact'
import { Route as ApiPublicShopifyWebhooksCustomersDataRequestRouteImport } from './routes/api/public/shopify/webhooks/customers-data-request'
import { Route as ApiPublicShopifyWebhooksCustomersRedactRouteImport } from './routes/api/public/shopify/webhooks/customers-redact'
import { Route as ApiPublicShopifyWebhooksShopRedactRouteImport } from './routes/api/public/shopify/webhooks/shop-redact'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFlagsRoute = AdminFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPermissionsRoute = ApiPermissionsRouteImport.update({
  id: '/api/permissions',
  path: '/api/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRouteRoute,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiToolsRoute = ApiAiToolsRouteImport.update({
  id: '/api/ai/tools',
  path: '/api/ai/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignsAudienceRoute = ApiCampaignsAudienceRouteImport.update({
  id: '/api/campaigns/audience',
  path: '/api/campaigns/audience',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignsControlRoute = ApiCampaignsControlRouteImport.update({
  id: '/api/campaigns/control',
  path: '/api/campaigns/control',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignsLaunchRoute = ApiCampaignsLaunchRouteImport.update({
  id: '/api/campaigns/launch',
  path: '/api/campaigns/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactsEvaluateSegmentRoute =
  ApiContactsEvaluateSegmentRouteImport.update({
    id: '/api/contacts/evaluate-segment',
    path: '/api/contacts/evaluate-segment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiContactsImportRoute = ApiContactsImportRouteImport.update({
  id: '/api/contacts/import',
  path: '/api/contacts/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsShopifyRoute = ApiIntegrationsShopifyRouteImport.update({
  id: '/api/integrations/shopify',
  path: '/api/integrations/shopify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalCampaignWorkerRoute =
  ApiInternalCampaignWorkerRouteImport.update({
    id: '/api/internal/campaign-worker',
    path: '/api/internal/campaign-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalFlowWorkerRoute = ApiInternalFlowWorkerRouteImport.update({
  id: '/api/internal/flow-worker',
  path: '/api/internal/flow-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalReprocessEventsRoute =
  ApiInternalReprocessEventsRouteImport.update({
    id: '/api/internal/reprocess-events',
    path: '/api/internal/reprocess-events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalShopifySyncWorkerRoute =
  ApiInternalShopifySyncWorkerRouteImport.update({
    id: '/api/internal/shopify-sync-worker',
    path: '/api/internal/shopify-sync-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalVersionRoute = ApiInternalVersionRouteImport.update({
  id: '/api/internal/version',
  path: '/api/internal/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopifyCallbackRoute =
  ApiPublicShopifyCallbackRouteImport.update({
    id: '/api/public/shopify-callback',
    path: '/api/public/shopify-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShopifyWebhookRoute = ApiPublicShopifyWebhookRouteImport.update({
  id: '/api/public/shopify-webhook',
  path: '/api/public/shopify-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp-webhook',
    path: '/api/public/whatsapp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWhatsappConnectRoute = ApiWhatsappConnectRouteImport.update({
  id: '/api/whatsapp/connect',
  path: '/api/whatsapp/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappEsConfigRoute = ApiWhatsappEsConfigRouteImport.update({
  id: '/api/whatsapp/es-config',
  path: '/api/whatsapp/es-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappEsExchangeRoute = ApiWhatsappEsExchangeRouteImport.update({
  id: '/api/whatsapp/es-exchange',
  path: '/api/whatsapp/es-exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappRefreshQualityRoute =
  ApiWhatsappRefreshQualityRouteImport.update({
    id: '/api/whatsapp/refresh-quality',
    path: '/api/whatsapp/refresh-quality',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWhatsappSendMessageRoute = ApiWhatsappSendMessageRouteImport.update({
  id: '/api/whatsapp/send-message',
  path: '/api/whatsapp/send-message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappTemplatesRoute = ApiWhatsappTemplatesRouteImport.update({
  id: '/api/whatsapp/templates',
  path: '/api/whatsapp/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappTokenStatusRoute = ApiWhatsappTokenStatusRouteImport.update({
  id: '/api/whatsapp/token-status',
  path: '/api/whatsapp/token-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCampaignsIdRoute = AppCampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFlowsIndexRoute = AppFlowsIndexRouteImport.update({
  id: '/flows/',
  path: '/flows/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiShopifyWebhooksCustomersDataRequestRoute =
  ApiShopifyWebhooksCustomersDataRequestRouteImport.update({
    id: '/api/shopify/webhooks/customers-data-request',
    path: '/api/shopify/webhooks/customers-data-request',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiShopifyWebhooksCustomersRedactRoute =
  ApiShopifyWebhooksCustomersRedactRouteImport.update({
    id: '/api/shopify/webhooks/customers-redact',
    path: '/api/shopify/webhooks/customers-redact',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiShopifyWebhooksShopRedactRoute =
  ApiShopifyWebhooksShopRedactRouteImport.update({
    id: '/api/shopify/webhooks/shop-redact',
    path: '/api/shopify/webhooks/shop-redact',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShopifyWebhooksCustomersDataRequestRoute =
  ApiPublicShopifyWebhooksCustomersDataRequestRouteImport.update({
    id: '/api/public/shopify/webhooks/customers-data-request',
    path: '/api/public/shopify/webhooks/customers-data-request',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShopifyWebhooksCustomersRedactRoute =
  ApiPublicShopifyWebhooksCustomersRedactRouteImport.update({
    id: '/api/public/shopify/webhooks/customers-redact',
    path: '/api/public/shopify/webhooks/customers-redact',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShopifyWebhooksShopRedactRoute =
  ApiPublicShopifyWebhooksShopRedactRouteImport.update({
    id: '/api/public/shopify/webhooks/shop-redact',
    path: '/api/public/shopify/webhooks/shop-redact',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/data-deletion': typeof DataDeletionRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/events': typeof ApiEventsRoute
  '/api/permissions': typeof ApiPermissionsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/automations': typeof AppAutomationsRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/join/$token': typeof JoinTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/ai/tools': typeof ApiAiToolsRoute
  '/api/campaigns/audience': typeof ApiCampaignsAudienceRoute
  '/api/campaigns/control': typeof ApiCampaignsControlRoute
  '/api/campaigns/launch': typeof ApiCampaignsLaunchRoute
  '/api/contacts/evaluate-segment': typeof ApiContactsEvaluateSegmentRoute
  '/api/contacts/import': typeof ApiContactsImportRoute
  '/api/integrations/shopify': typeof ApiIntegrationsShopifyRoute
  '/api/internal/campaign-worker': typeof ApiInternalCampaignWorkerRoute
  '/api/internal/flow-worker': typeof ApiInternalFlowWorkerRoute
  '/api/internal/reprocess-events': typeof ApiInternalReprocessEventsRoute
  '/api/internal/shopify-sync-worker': typeof ApiInternalShopifySyncWorkerRoute
  '/api/internal/version': typeof ApiInternalVersionRoute
  '/api/public/shopify-callback': typeof ApiPublicShopifyCallbackRoute
  '/api/public/shopify-webhook': typeof ApiPublicShopifyWebhookRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/whatsapp/connect': typeof ApiWhatsappConnectRoute
  '/api/whatsapp/es-config': typeof ApiWhatsappEsConfigRoute
  '/api/whatsapp/es-exchange': typeof ApiWhatsappEsExchangeRoute
  '/api/whatsapp/refresh-quality': typeof ApiWhatsappRefreshQualityRoute
  '/api/whatsapp/send-message': typeof ApiWhatsappSendMessageRoute
  '/api/whatsapp/templates': typeof ApiWhatsappTemplatesRoute
  '/api/whatsapp/token-status': typeof ApiWhatsappTokenStatusRoute
  '/app/campaigns/$id': typeof AppCampaignsIdRoute
  '/app/campaigns/': typeof AppCampaignsIndexRoute
  '/app/flows/': typeof AppFlowsIndexRoute
  '/api/shopify/webhooks/customers-data-request': typeof ApiShopifyWebhooksCustomersDataRequestRoute
  '/api/shopify/webhooks/customers-redact': typeof ApiShopifyWebhooksCustomersRedactRoute
  '/api/shopify/webhooks/shop-redact': typeof ApiShopifyWebhooksShopRedactRoute
  '/api/public/shopify/webhooks/customers-data-request': typeof ApiPublicShopifyWebhooksCustomersDataRequestRoute
  '/api/public/shopify/webhooks/customers-redact': typeof ApiPublicShopifyWebhooksCustomersRedactRoute
  '/api/public/shopify/webhooks/shop-redact': typeof ApiPublicShopifyWebhooksShopRedactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-deletion': typeof DataDeletionRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/events': typeof ApiEventsRoute
  '/api/permissions': typeof ApiPermissionsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/automations': typeof AppAutomationsRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/join/$token': typeof JoinTokenRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/api/ai/tools': typeof ApiAiToolsRoute
  '/api/campaigns/audience': typeof ApiCampaignsAudienceRoute
  '/api/campaigns/control': typeof ApiCampaignsControlRoute
  '/api/campaigns/launch': typeof ApiCampaignsLaunchRoute
  '/api/contacts/evaluate-segment': typeof ApiContactsEvaluateSegmentRoute
  '/api/contacts/import': typeof ApiContactsImportRoute
  '/api/integrations/shopify': typeof ApiIntegrationsShopifyRoute
  '/api/internal/campaign-worker': typeof ApiInternalCampaignWorkerRoute
  '/api/internal/flow-worker': typeof ApiInternalFlowWorkerRoute
  '/api/internal/reprocess-events': typeof ApiInternalReprocessEventsRoute
  '/api/internal/shopify-sync-worker': typeof ApiInternalShopifySyncWorkerRoute
  '/api/internal/version': typeof ApiInternalVersionRoute
  '/api/public/shopify-callback': typeof ApiPublicShopifyCallbackRoute
  '/api/public/shopify-webhook': typeof ApiPublicShopifyWebhookRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/whatsapp/connect': typeof ApiWhatsappConnectRoute
  '/api/whatsapp/es-config': typeof ApiWhatsappEsConfigRoute
  '/api/whatsapp/es-exchange': typeof ApiWhatsappEsExchangeRoute
  '/api/whatsapp/refresh-quality': typeof ApiWhatsappRefreshQualityRoute
  '/api/whatsapp/send-message': typeof ApiWhatsappSendMessageRoute
  '/api/whatsapp/templates': typeof ApiWhatsappTemplatesRoute
  '/api/whatsapp/token-status': typeof ApiWhatsappTokenStatusRoute
  '/app/campaigns/$id': typeof AppCampaignsIdRoute
  '/app/campaigns': typeof AppCampaignsIndexRoute
  '/app/flows': typeof AppFlowsIndexRoute
  '/api/shopify/webhooks/customers-data-request': typeof ApiShopifyWebhooksCustomersDataRequestRoute
  '/api/shopify/webhooks/customers-redact': typeof ApiShopifyWebhooksCustomersRedactRoute
  '/api/shopify/webhooks/shop-redact': typeof ApiShopifyWebhooksShopRedactRoute
  '/api/public/shopify/webhooks/customers-data-request': typeof ApiPublicShopifyWebhooksCustomersDataRequestRoute
  '/api/public/shopify/webhooks/customers-redact': typeof ApiPublicShopifyWebhooksCustomersRedactRoute
  '/api/public/shopify/webhooks/shop-redact': typeof ApiPublicShopifyWebhooksShopRedactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/data-deletion': typeof DataDeletionRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/events': typeof ApiEventsRoute
  '/api/permissions': typeof ApiPermissionsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/automations': typeof AppAutomationsRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/join/$token': typeof JoinTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/ai/tools': typeof ApiAiToolsRoute
  '/api/campaigns/audience': typeof ApiCampaignsAudienceRoute
  '/api/campaigns/control': typeof ApiCampaignsControlRoute
  '/api/campaigns/launch': typeof ApiCampaignsLaunchRoute
  '/api/contacts/evaluate-segment': typeof ApiContactsEvaluateSegmentRoute
  '/api/contacts/import': typeof ApiContactsImportRoute
  '/api/integrations/shopify': typeof ApiIntegrationsShopifyRoute
  '/api/internal/campaign-worker': typeof ApiInternalCampaignWorkerRoute
  '/api/internal/flow-worker': typeof ApiInternalFlowWorkerRoute
  '/api/internal/reprocess-events': typeof ApiInternalReprocessEventsRoute
  '/api/internal/shopify-sync-worker': typeof ApiInternalShopifySyncWorkerRoute
  '/api/internal/version': typeof ApiInternalVersionRoute
  '/api/public/shopify-callback': typeof ApiPublicShopifyCallbackRoute
  '/api/public/shopify-webhook': typeof ApiPublicShopifyWebhookRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/whatsapp/connect': typeof ApiWhatsappConnectRoute
  '/api/whatsapp/es-config': typeof ApiWhatsappEsConfigRoute
  '/api/whatsapp/es-exchange': typeof ApiWhatsappEsExchangeRoute
  '/api/whatsapp/refresh-quality': typeof ApiWhatsappRefreshQualityRoute
  '/api/whatsapp/send-message': typeof ApiWhatsappSendMessageRoute
  '/api/whatsapp/templates': typeof ApiWhatsappTemplatesRoute
  '/api/whatsapp/token-status': typeof ApiWhatsappTokenStatusRoute
  '/app/campaigns/$id': typeof AppCampaignsIdRoute
  '/app/campaigns/': typeof AppCampaignsIndexRoute
  '/app/flows/': typeof AppFlowsIndexRoute
  '/api/shopify/webhooks/customers-data-request': typeof ApiShopifyWebhooksCustomersDataRequestRoute
  '/api/shopify/webhooks/customers-redact': typeof ApiShopifyWebhooksCustomersRedactRoute
  '/api/shopify/webhooks/shop-redact': typeof ApiShopifyWebhooksShopRedactRoute
  '/api/public/shopify/webhooks/customers-data-request': typeof ApiPublicShopifyWebhooksCustomersDataRequestRoute
  '/api/public/shopify/webhooks/customers-redact': typeof ApiPublicShopifyWebhooksCustomersRedactRoute
  '/api/public/shopify/webhooks/shop-redact': typeof ApiPublicShopifyWebhooksShopRedactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/data-deletion'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/activity'
    | '/admin/flags'
    | '/admin/organizations'
    | '/admin/users'
    | '/api/events'
    | '/api/permissions'
    | '/app/analytics'
    | '/app/automations'
    | '/app/contacts'
    | '/app/inbox'
    | '/app/settings'
    | '/app/templates'
    | '/join/$token'
    | '/admin/'
    | '/app/'
    | '/api/ai/tools'
    | '/api/campaigns/audience'
    | '/api/campaigns/control'
    | '/api/campaigns/launch'
    | '/api/contacts/evaluate-segment'
    | '/api/contacts/import'
    | '/api/integrations/shopify'
    | '/api/internal/campaign-worker'
    | '/api/internal/flow-worker'
    | '/api/internal/reprocess-events'
    | '/api/internal/shopify-sync-worker'
    | '/api/internal/version'
    | '/api/public/shopify-callback'
    | '/api/public/shopify-webhook'
    | '/api/public/whatsapp-webhook'
    | '/api/whatsapp/connect'
    | '/api/whatsapp/es-config'
    | '/api/whatsapp/es-exchange'
    | '/api/whatsapp/refresh-quality'
    | '/api/whatsapp/send-message'
    | '/api/whatsapp/templates'
    | '/api/whatsapp/token-status'
    | '/app/campaigns/$id'
    | '/app/campaigns/'
    | '/app/flows/'
    | '/api/shopify/webhooks/customers-data-request'
    | '/api/shopify/webhooks/customers-redact'
    | '/api/shopify/webhooks/shop-redact'
    | '/api/public/shopify/webhooks/customers-data-request'
    | '/api/public/shopify/webhooks/customers-redact'
    | '/api/public/shopify/webhooks/shop-redact'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-deletion'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/activity'
    | '/admin/flags'
    | '/admin/organizations'
    | '/admin/users'
    | '/api/events'
    | '/api/permissions'
    | '/app/analytics'
    | '/app/automations'
    | '/app/contacts'
    | '/app/inbox'
    | '/app/settings'
    | '/app/templates'
    | '/join/$token'
    | '/admin'
    | '/app'
    | '/api/ai/tools'
    | '/api/campaigns/audience'
    | '/api/campaigns/control'
    | '/api/campaigns/launch'
    | '/api/contacts/evaluate-segment'
    | '/api/contacts/import'
    | '/api/integrations/shopify'
    | '/api/internal/campaign-worker'
    | '/api/internal/flow-worker'
    | '/api/internal/reprocess-events'
    | '/api/internal/shopify-sync-worker'
    | '/api/internal/version'
    | '/api/public/shopify-callback'
    | '/api/public/shopify-webhook'
    | '/api/public/whatsapp-webhook'
    | '/api/whatsapp/connect'
    | '/api/whatsapp/es-config'
    | '/api/whatsapp/es-exchange'
    | '/api/whatsapp/refresh-quality'
    | '/api/whatsapp/send-message'
    | '/api/whatsapp/templates'
    | '/api/whatsapp/token-status'
    | '/app/campaigns/$id'
    | '/app/campaigns'
    | '/app/flows'
    | '/api/shopify/webhooks/customers-data-request'
    | '/api/shopify/webhooks/customers-redact'
    | '/api/shopify/webhooks/shop-redact'
    | '/api/public/shopify/webhooks/customers-data-request'
    | '/api/public/shopify/webhooks/customers-redact'
    | '/api/public/shopify/webhooks/shop-redact'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/data-deletion'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/activity'
    | '/admin/flags'
    | '/admin/organizations'
    | '/admin/users'
    | '/api/events'
    | '/api/permissions'
    | '/app/analytics'
    | '/app/automations'
    | '/app/contacts'
    | '/app/inbox'
    | '/app/settings'
    | '/app/templates'
    | '/join/$token'
    | '/admin/'
    | '/app/'
    | '/api/ai/tools'
    | '/api/campaigns/audience'
    | '/api/campaigns/control'
    | '/api/campaigns/launch'
    | '/api/contacts/evaluate-segment'
    | '/api/contacts/import'
    | '/api/integrations/shopify'
    | '/api/internal/campaign-worker'
    | '/api/internal/flow-worker'
    | '/api/internal/reprocess-events'
    | '/api/internal/shopify-sync-worker'
    | '/api/internal/version'
    | '/api/public/shopify-callback'
    | '/api/public/shopify-webhook'
    | '/api/public/whatsapp-webhook'
    | '/api/whatsapp/connect'
    | '/api/whatsapp/es-config'
    | '/api/whatsapp/es-exchange'
    | '/api/whatsapp/refresh-quality'
    | '/api/whatsapp/send-message'
    | '/api/whatsapp/templates'
    | '/api/whatsapp/token-status'
    | '/app/campaigns/$id'
    | '/app/campaigns/'
    | '/app/flows/'
    | '/api/shopify/webhooks/customers-data-request'
    | '/api/shopify/webhooks/customers-redact'
    | '/api/shopify/webhooks/shop-redact'
    | '/api/public/shopify/webhooks/customers-data-request'
    | '/api/public/shopify/webhooks/customers-redact'
    | '/api/public/shopify/webhooks/shop-redact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DataDeletionRoute: typeof DataDeletionRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiPermissionsRoute: typeof ApiPermissionsRoute
  JoinTokenRoute: typeof JoinTokenRoute
  ApiAiToolsRoute: typeof ApiAiToolsRoute
  ApiCampaignsAudienceRoute: typeof ApiCampaignsAudienceRoute
  ApiCampaignsControlRoute: typeof ApiCampaignsControlRoute
  ApiCampaignsLaunchRoute: typeof ApiCampaignsLaunchRoute
  ApiContactsEvaluateSegmentRoute: typeof ApiContactsEvaluateSegmentRoute
  ApiContactsImportRoute: typeof ApiContactsImportRoute
  ApiIntegrationsShopifyRoute: typeof ApiIntegrationsShopifyRoute
  ApiInternalCampaignWorkerRoute: typeof ApiInternalCampaignWorkerRoute
  ApiInternalFlowWorkerRoute: typeof ApiInternalFlowWorkerRoute
  ApiInternalReprocessEventsRoute: typeof ApiInternalReprocessEventsRoute
  ApiInternalShopifySyncWorkerRoute: typeof ApiInternalShopifySyncWorkerRoute
  ApiInternalVersionRoute: typeof ApiInternalVersionRoute
  ApiPublicShopifyCallbackRoute: typeof ApiPublicShopifyCallbackRoute
  ApiPublicShopifyWebhookRoute: typeof ApiPublicShopifyWebhookRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  ApiWhatsappConnectRoute: typeof ApiWhatsappConnectRoute
  ApiWhatsappEsConfigRoute: typeof ApiWhatsappEsConfigRoute
  ApiWhatsappEsExchangeRoute: typeof ApiWhatsappEsExchangeRoute
  ApiWhatsappRefreshQualityRoute: typeof ApiWhatsappRefreshQualityRoute
  ApiWhatsappSendMessageRoute: typeof ApiWhatsappSendMessageRoute
  ApiWhatsappTemplatesRoute: typeof ApiWhatsappTemplatesRoute
  ApiWhatsappTokenStatusRoute: typeof ApiWhatsappTokenStatusRoute
  ApiShopifyWebhooksCustomersDataRequestRoute: typeof ApiShopifyWebhooksCustomersDataRequestRoute
  ApiShopifyWebhooksCustomersRedactRoute: typeof ApiShopifyWebhooksCustomersRedactRoute
  ApiShopifyWebhooksShopRedactRoute: typeof ApiShopifyWebhooksShopRedactRoute
  ApiPublicShopifyWebhooksCustomersDataRequestRoute: typeof ApiPublicShopifyWebhooksCustomersDataRequestRoute
  ApiPublicShopifyWebhooksCustomersRedactRoute: typeof ApiPublicShopifyWebhooksCustomersRedactRoute
  ApiPublicShopifyWebhooksShopRedactRoute: typeof ApiPublicShopifyWebhooksShopRedactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/flags': {
      id: '/admin/flags'
      path: '/flags'
      fullPath: '/admin/flags'
      preLoaderRoute: typeof AdminFlagsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/permissions': {
      id: '/api/permissions'
      path: '/api/permissions'
      fullPath: '/api/permissions'
      preLoaderRoute: typeof ApiPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/automations': {
      id: '/app/automations'
      path: '/automations'
      fullPath: '/app/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/contacts': {
      id: '/app/contacts'
      path: '/contacts'
      fullPath: '/app/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/templates': {
      id: '/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/tools': {
      id: '/api/ai/tools'
      path: '/api/ai/tools'
      fullPath: '/api/ai/tools'
      preLoaderRoute: typeof ApiAiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns/audience': {
      id: '/api/campaigns/audience'
      path: '/api/campaigns/audience'
      fullPath: '/api/campaigns/audience'
      preLoaderRoute: typeof ApiCampaignsAudienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns/control': {
      id: '/api/campaigns/control'
      path: '/api/campaigns/control'
      fullPath: '/api/campaigns/control'
      preLoaderRoute: typeof ApiCampaignsControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns/launch': {
      id: '/api/campaigns/launch'
      path: '/api/campaigns/launch'
      fullPath: '/api/campaigns/launch'
      preLoaderRoute: typeof ApiCampaignsLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contacts/evaluate-segment': {
      id: '/api/contacts/evaluate-segment'
      path: '/api/contacts/evaluate-segment'
      fullPath: '/api/contacts/evaluate-segment'
      preLoaderRoute: typeof ApiContactsEvaluateSegmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contacts/import': {
      id: '/api/contacts/import'
      path: '/api/contacts/import'
      fullPath: '/api/contacts/import'
      preLoaderRoute: typeof ApiContactsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/shopify': {
      id: '/api/integrations/shopify'
      path: '/api/integrations/shopify'
      fullPath: '/api/integrations/shopify'
      preLoaderRoute: typeof ApiIntegrationsShopifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/campaign-worker': {
      id: '/api/internal/campaign-worker'
      path: '/api/internal/campaign-worker'
      fullPath: '/api/internal/campaign-worker'
      preLoaderRoute: typeof ApiInternalCampaignWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/flow-worker': {
      id: '/api/internal/flow-worker'
      path: '/api/internal/flow-worker'
      fullPath: '/api/internal/flow-worker'
      preLoaderRoute: typeof ApiInternalFlowWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/reprocess-events': {
      id: '/api/internal/reprocess-events'
      path: '/api/internal/reprocess-events'
      fullPath: '/api/internal/reprocess-events'
      preLoaderRoute: typeof ApiInternalReprocessEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/shopify-sync-worker': {
      id: '/api/internal/shopify-sync-worker'
      path: '/api/internal/shopify-sync-worker'
      fullPath: '/api/internal/shopify-sync-worker'
      preLoaderRoute: typeof ApiInternalShopifySyncWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/version': {
      id: '/api/internal/version'
      path: '/api/internal/version'
      fullPath: '/api/internal/version'
      preLoaderRoute: typeof ApiInternalVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify-callback': {
      id: '/api/public/shopify-callback'
      path: '/api/public/shopify-callback'
      fullPath: '/api/public/shopify-callback'
      preLoaderRoute: typeof ApiPublicShopifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify-webhook': {
      id: '/api/public/shopify-webhook'
      path: '/api/public/shopify-webhook'
      fullPath: '/api/public/shopify-webhook'
      preLoaderRoute: typeof ApiPublicShopifyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp-webhook': {
      id: '/api/public/whatsapp-webhook'
      path: '/api/public/whatsapp-webhook'
      fullPath: '/api/public/whatsapp-webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/connect': {
      id: '/api/whatsapp/connect'
      path: '/api/whatsapp/connect'
      fullPath: '/api/whatsapp/connect'
      preLoaderRoute: typeof ApiWhatsappConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/es-config': {
      id: '/api/whatsapp/es-config'
      path: '/api/whatsapp/es-config'
      fullPath: '/api/whatsapp/es-config'
      preLoaderRoute: typeof ApiWhatsappEsConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/es-exchange': {
      id: '/api/whatsapp/es-exchange'
      path: '/api/whatsapp/es-exchange'
      fullPath: '/api/whatsapp/es-exchange'
      preLoaderRoute: typeof ApiWhatsappEsExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/refresh-quality': {
      id: '/api/whatsapp/refresh-quality'
      path: '/api/whatsapp/refresh-quality'
      fullPath: '/api/whatsapp/refresh-quality'
      preLoaderRoute: typeof ApiWhatsappRefreshQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/send-message': {
      id: '/api/whatsapp/send-message'
      path: '/api/whatsapp/send-message'
      fullPath: '/api/whatsapp/send-message'
      preLoaderRoute: typeof ApiWhatsappSendMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/templates': {
      id: '/api/whatsapp/templates'
      path: '/api/whatsapp/templates'
      fullPath: '/api/whatsapp/templates'
      preLoaderRoute: typeof ApiWhatsappTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/token-status': {
      id: '/api/whatsapp/token-status'
      path: '/api/whatsapp/token-status'
      fullPath: '/api/whatsapp/token-status'
      preLoaderRoute: typeof ApiWhatsappTokenStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/campaigns/': {
      id: '/app/campaigns/'
      path: '/campaigns'
      fullPath: '/app/campaigns/'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/campaigns/$id': {
      id: '/app/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/app/campaigns/$id'
      preLoaderRoute: typeof AppCampaignsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/flows/': {
      id: '/app/flows/'
      path: '/flows'
      fullPath: '/app/flows/'
      preLoaderRoute: typeof AppFlowsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/shopify/webhooks/customers-data-request': {
      id: '/api/shopify/webhooks/customers-data-request'
      path: '/api/shopify/webhooks/customers-data-request'
      fullPath: '/api/shopify/webhooks/customers-data-request'
      preLoaderRoute: typeof ApiShopifyWebhooksCustomersDataRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/webhooks/customers-redact': {
      id: '/api/shopify/webhooks/customers-redact'
      path: '/api/shopify/webhooks/customers-redact'
      fullPath: '/api/shopify/webhooks/customers-redact'
      preLoaderRoute: typeof ApiShopifyWebhooksCustomersRedactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/webhooks/shop-redact': {
      id: '/api/shopify/webhooks/shop-redact'
      path: '/api/shopify/webhooks/shop-redact'
      fullPath: '/api/shopify/webhooks/shop-redact'
      preLoaderRoute: typeof ApiShopifyWebhooksShopRedactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/webhooks/customers-data-request': {
      id: '/api/public/shopify/webhooks/customers-data-request'
      path: '/api/public/shopify/webhooks/customers-data-request'
      fullPath: '/api/public/shopify/webhooks/customers-data-request'
      preLoaderRoute: typeof ApiPublicShopifyWebhooksCustomersDataRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/webhooks/customers-redact': {
      id: '/api/public/shopify/webhooks/customers-redact'
      path: '/api/public/shopify/webhooks/customers-redact'
      fullPath: '/api/public/shopify/webhooks/customers-redact'
      preLoaderRoute: typeof ApiPublicShopifyWebhooksCustomersRedactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/webhooks/shop-redact': {
      id: '/api/public/shopify/webhooks/shop-redact'
      path: '/api/public/shopify/webhooks/shop-redact'
      fullPath: '/api/public/shopify/webhooks/shop-redact'
      preLoaderRoute: typeof ApiPublicShopifyWebhooksShopRedactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminFlagsRoute: typeof AdminFlagsRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminFlagsRoute: AdminFlagsRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppContactsRoute: typeof AppContactsRoute
  AppInboxRoute: typeof AppInboxRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCampaignsIdRoute: typeof AppCampaignsIdRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
  AppFlowsIndexRoute: typeof AppFlowsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAutomationsRoute: AppAutomationsRoute,
  AppContactsRoute: AppContactsRoute,
  AppInboxRoute: AppInboxRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppIndexRoute: AppIndexRoute,
  AppCampaignsIdRoute: AppCampaignsIdRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
  AppFlowsIndexRoute: AppFlowsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  DataDeletionRoute: DataDeletionRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiPermissionsRoute: ApiPermissionsRoute,
  JoinTokenRoute: JoinTokenRoute,
  ApiAiToolsRoute: ApiAiToolsRoute,
  ApiCampaignsAudienceRoute: ApiCampaignsAudienceRoute,
  ApiCampaignsControlRoute: ApiCampaignsControlRoute,
  ApiCampaignsLaunchRoute: ApiCampaignsLaunchRoute,
  ApiContactsEvaluateSegmentRoute: ApiContactsEvaluateSegmentRoute,
  ApiContactsImportRoute: ApiContactsImportRoute,
  ApiIntegrationsShopifyRoute: ApiIntegrationsShopifyRoute,
  ApiInternalCampaignWorkerRoute: ApiInternalCampaignWorkerRoute,
  ApiInternalFlowWorkerRoute: ApiInternalFlowWorkerRoute,
  ApiInternalReprocessEventsRoute: ApiInternalReprocessEventsRoute,
  ApiInternalShopifySyncWorkerRoute: ApiInternalShopifySyncWorkerRoute,
  ApiInternalVersionRoute: ApiInternalVersionRoute,
  ApiPublicShopifyCallbackRoute: ApiPublicShopifyCallbackRoute,
  ApiPublicShopifyWebhookRoute: ApiPublicShopifyWebhookRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  ApiWhatsappConnectRoute: ApiWhatsappConnectRoute,
  ApiWhatsappEsConfigRoute: ApiWhatsappEsConfigRoute,
  ApiWhatsappEsExchangeRoute: ApiWhatsappEsExchangeRoute,
  ApiWhatsappRefreshQualityRoute: ApiWhatsappRefreshQualityRoute,
  ApiWhatsappSendMessageRoute: ApiWhatsappSendMessageRoute,
  ApiWhatsappTemplatesRoute: ApiWhatsappTemplatesRoute,
  ApiWhatsappTokenStatusRoute: ApiWhatsappTokenStatusRoute,
  ApiShopifyWebhooksCustomersDataRequestRoute:
    ApiShopifyWebhooksCustomersDataRequestRoute,
  ApiShopifyWebhooksCustomersRedactRoute:
    ApiShopifyWebhooksCustomersRedactRoute,
  ApiShopifyWebhooksShopRedactRoute: ApiShopifyWebhooksShopRedactRoute,
  ApiPublicShopifyWebhooksCustomersDataRequestRoute:
    ApiPublicShopifyWebhooksCustomersDataRequestRoute,
  ApiPublicShopifyWebhooksCustomersRedactRoute:
    ApiPublicShopifyWebhooksCustomersRedactRoute,
  ApiPublicShopifyWebhooksShopRedactRoute:
    ApiPublicShopifyWebhooksShopRedactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
